"""wortpaket_topic_zipf_index

Revision ID: 281e10e7f944
Revises: b8e2f47a1c93
Create Date: 2026-07-29 00:51:07.796471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '281e10e7f944'
down_revision: Union[str, Sequence[str], None] = 'b8e2f47a1c93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_vocab_cards_topic_zipf', 'vocab_cards', ['topic', 'zipf'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vocab_cards_topic_zipf', table_name='vocab_cards')
    # ### end Alembic commands ###
