"""initial schema

Revision ID: 678b5be647b5
Revises: 
Create Date: 2026-07-10 23:06:28.397066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '678b5be647b5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('essays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('essay_type', sa.String(length=64), nullable=False),
    sa.Column('topic', sa.String(length=128), nullable=False),
    sa.Column('level', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phrases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text_de', sa.Text(), nullable=False),
    sa.Column('translation_ru', sa.Text(), nullable=False),
    sa.Column('essay_part', sa.String(length=64), nullable=False),
    sa.Column('topic', sa.String(length=64), nullable=True),
    sa.Column('level', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pipeline_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('words_added', sa.Integer(), nullable=False),
    sa.Column('words_linked', sa.Integer(), nullable=False),
    sa.Column('phrases_added', sa.Integer(), nullable=False),
    sa.Column('target_words', sa.Integer(), nullable=False),
    sa.Column('errors_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topic_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('target_words', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_run_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic', name='uq_topic_queue_topic')
    )
    op.create_table('user_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('streak_current', sa.Integer(), nullable=False),
    sa.Column('streak_last_date', sa.Date(), nullable=True),
    sa.Column('total_words_learned', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('word_failures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=255), nullable=False),
    sa.Column('topic', sa.String(length=128), nullable=False),
    sa.Column('pos', sa.String(length=32), nullable=False),
    sa.Column('article', sa.String(length=16), nullable=True),
    sa.Column('examples', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word', 'topic', name='uq_failure_word_topic')
    )
    op.create_table('words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('german', sa.String(length=255), nullable=False),
    sa.Column('article', sa.String(length=16), nullable=True),
    sa.Column('word_type', sa.String(length=32), nullable=False),
    sa.Column('translation_ru', sa.Text(), nullable=False),
    sa.Column('level', sa.String(length=8), nullable=False),
    sa.Column('grammar_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('examples', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('essay_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('essay_id', sa.Integer(), nullable=False),
    sa.Column('errors_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('grade', sa.String(length=4), nullable=True),
    sa.Column('text_snapshot', sa.Text(), nullable=True),
    sa.Column('part_reports_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('final_summary_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['essay_id'], ['essays.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_phrase_known',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('phrase_id', sa.Integer(), nullable=False),
    sa.Column('known', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['phrase_id'], ['phrases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'phrase_id', name='uq_user_phrase')
    )
    op.create_table('user_word_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('times_correct', sa.Integer(), nullable=False),
    sa.Column('times_wrong', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'word_id', name='uq_user_word')
    )
    op.create_table('word_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word_id', 'topic', name='uq_word_topic')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word_topics')
    op.drop_table('user_word_progress')
    op.drop_table('user_phrase_known')
    op.drop_table('essay_analyses')
    op.drop_table('words')
    op.drop_table('word_failures')
    op.drop_table('user_stats')
    op.drop_table('topic_queue')
    op.drop_table('pipeline_runs')
    op.drop_table('phrases')
    op.drop_table('essays')
    # ### end Alembic commands ###
