"""vocab_cards.zipf — frequency for search ranking

Revision ID: d4e6a1f30b92
Revises: 88b9d9797836
Create Date: 2026-07-17

Additive: one nullable column plus its index.

Why: every exact translation hit scores identically under pg_trgm, so ordering
fell through to `length(lemma_norm)` — which ranked `schnell` (zipf 5.51, the
354th most common German word) LAST for "быстрый", below fix, rasch, prompt,
rapide and zügig. The frequency was in vocab.db for all 108k source words the
whole time and was simply never carried into the mirror.

Backfilled by `enrich.plan_repairs()` on the SQLite side and then re-mirrored, so
the column arrives empty here and fills on the next sync. NULL sorts last under
`NULLS LAST`, which is the right default for the handful of cards with no source
row (pre-1996 spellings filed under their modern form).

Written by hand rather than autogenerated: this database carries known, harmless
constraint drift (documented in 88b9d9797836) that autogenerate keeps proposing
to drop, and that must not ride along with an unrelated column.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "d4e6a1f30b92"
down_revision: Union[str, Sequence[str], None] = "88b9d9797836"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column("vocab_cards", sa.Column("zipf", sa.Float(), nullable=True))
    op.create_index("ix_vocab_cards_zipf", "vocab_cards", ["zipf"])


def downgrade() -> None:
    op.drop_index("ix_vocab_cards_zipf", table_name="vocab_cards")
    op.drop_column("vocab_cards", "zipf")
