"""essay_word_packages

Revision ID: da19fea5d453
Revises: 281e10e7f944
Create Date: 2026-07-29 00:58:45.941249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'da19fea5d453'
down_revision: Union[str, Sequence[str], None] = '281e10e7f944'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('essay_word_packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('essay_id', sa.Integer(), nullable=False),
    sa.Column('thema', sa.Text(), nullable=False),
    sa.Column('niveau', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('lemmas', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('stats', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['essay_id'], ['essays.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('essay_id', name='uq_essay_word_package_essay')
    )
    op.create_index(op.f('ix_essay_word_packages_essay_id'), 'essay_word_packages', ['essay_id'], unique=False)
    op.create_index('ix_essay_word_packages_status', 'essay_word_packages', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_essay_word_packages_status', table_name='essay_word_packages')
    op.drop_index(op.f('ix_essay_word_packages_essay_id'), table_name='essay_word_packages')
    op.drop_table('essay_word_packages')
    # ### end Alembic commands ###
