"""vocab_cards.form_kind/form_of — headwords apart from word forms

Revision ID: e7c9b04a51f6
Revises: d4e6a1f30b92
Create Date: 2026-07-19

Additive: two nullable columns plus a partial index.

Why: `vocab.db` is a bilingual-dictionary dump, and a dictionary lists forms next
to headwords — participles (`gemacht`), plurals (`Fakten`), combining forms
(`Schnell-` "в сл. сл."), bare cross-references (`alleine` → "см. allein").
Enrichment gave each one a card. They then outrank real words, because
`wordfreq` folds case and counts surface forms: `Schnell` is handed the 5.51 of
the adjective `schnell`, and ranking consults `zipf` immediately after the match
score. Measured on the live base, non-words are 16% of the zipf 4–5 band against
1% below zipf 2 — the contamination is concentrated exactly where people look.

Tagged, not deleted: `gemacht` stays findable and renders as "форма от machen",
the way Yandex.Dictionary and Linguee present forms. Only the head of a result
list is at stake.

Populated by `vocab.forms.tag_forms()` on the SQLite side and carried over by the
mirror, so the columns arrive empty here and fill on the next sync.

The index is partial because the tagged rows are the small minority (~3% of the
base) and every query that uses the column asks for non-NULL.

Written by hand rather than autogenerated: this database carries known, harmless
constraint drift (documented in 88b9d9797836) that autogenerate keeps proposing
to drop, and that must not ride along with an unrelated column.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "e7c9b04a51f6"
down_revision: Union[str, Sequence[str], None] = "d4e6a1f30b92"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column("vocab_cards", sa.Column("form_kind", sa.String(16), nullable=True))
    op.add_column("vocab_cards", sa.Column("form_of", sa.String(128), nullable=True))
    op.create_index(
        "ix_vocab_cards_form_kind", "vocab_cards", ["form_kind"],
        postgresql_where=sa.text("form_kind IS NOT NULL"),
    )


def downgrade() -> None:
    op.drop_index("ix_vocab_cards_form_kind", table_name="vocab_cards")
    op.drop_column("vocab_cards", "form_of")
    op.drop_column("vocab_cards", "form_kind")
