"""vocab_cards.morphology — full inflection paradigms

Revision ID: f2a80d6c9e13
Revises: e7c9b04a51f6
Create Date: 2026-07-19

Additive: one nullable JSON column, no index (it is read with the card it hangs
off, never searched on).

Why: what the enrichment model writes into `data["grammar"]` is three fields per
verb and two per noun — enough to recognise a word, not enough to use one. The
present tense is absent entirely, so `du gibst` / `er gibt`, the stem change
drilled hardest at A2–B1, appears nowhere. Nouns carry Genitiv and Plural but no
Dativ, which hides the n-declension: `Student` stored "des Studenten / die
Studenten" and left "dem Student" vs "dem Studenten" unanswered.

Filled by `vocab.morph.import_dump()` from a German Wiktionary dump — a join,
not a model call. Measured on the live base: 48 403 of 76 332 cards (63.4%) get
a paradigm; the rest have no Wiktionary entry and stay NULL, which the card
renderer treats as "show what the model gave us".

Arrives empty here and fills on the next mirror pass, like zipf and form_kind
before it.

Written by hand rather than autogenerated: this database carries known, harmless
constraint drift (documented in 88b9d9797836) that autogenerate keeps proposing
to drop, and that must not ride along with an unrelated column.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f2a80d6c9e13"
down_revision: Union[str, Sequence[str], None] = "e7c9b04a51f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column("vocab_cards",
                  sa.Column("morphology", postgresql.JSONB(), nullable=True))


def downgrade() -> None:
    op.drop_column("vocab_cards", "morphology")
